title: 文章集散地
description: 收集寫過的文章
base: /articles/
dest: dist
themeConfig:
  sidebar:
    - title: 鐵人賽系列文章
      children:
        - title: CI 從入門到入坑
          children:
            - ['/src/ironman-intro-of-ci/', '序']
            - /src/ironman-intro-of-ci/day01
            - /src/ironman-intro-of-ci/day02
            - /src/ironman-intro-of-ci/day03
            - /src/ironman-intro-of-ci/day04
            - /src/ironman-intro-of-ci/day05
            - /src/ironman-intro-of-ci/day06
            - /src/ironman-intro-of-ci/day07
            - /src/ironman-intro-of-ci/day08
            - /src/ironman-intro-of-ci/day09
            - /src/ironman-intro-of-ci/day10
            - /src/ironman-intro-of-ci/day11
            - /src/ironman-intro-of-ci/day12
            - /src/ironman-intro-of-ci/day13
            - /src/ironman-intro-of-ci/day14
            - /src/ironman-intro-of-ci/day15
            - /src/ironman-intro-of-ci/day16
            - /src/ironman-intro-of-ci/day17
            - /src/ironman-intro-of-ci/day18
            - /src/ironman-intro-of-ci/day19
            - /src/ironman-intro-of-ci/day20
            - /src/ironman-intro-of-ci/day21
            - /src/ironman-intro-of-ci/day22
            - /src/ironman-intro-of-ci/day23
            - /src/ironman-intro-of-ci/day24
            - /src/ironman-intro-of-ci/day25
            - /src/ironman-intro-of-ci/day26
            - /src/ironman-intro-of-ci/day27
            - /src/ironman-intro-of-ci/day28
            - /src/ironman-intro-of-ci/day29
            - /src/ironman-intro-of-ci/day30
        - title: 看到 code 寫成這樣我也是醉了，不如試試重構？
          children:
            - ['/src/ironman-refactoring-30-days/', '序']
            - /src/ironman-refactoring-30-days/day01
            - /src/ironman-refactoring-30-days/day02
            - /src/ironman-refactoring-30-days/day03
            - /src/ironman-refactoring-30-days/day04
            - /src/ironman-refactoring-30-days/day05
            - /src/ironman-refactoring-30-days/day06
            - /src/ironman-refactoring-30-days/day07
            - /src/ironman-refactoring-30-days/day08
            - /src/ironman-refactoring-30-days/day09
            - /src/ironman-refactoring-30-days/day10
            - /src/ironman-refactoring-30-days/day11
            - /src/ironman-refactoring-30-days/day12
            - /src/ironman-refactoring-30-days/day13
            - /src/ironman-refactoring-30-days/day14
            - /src/ironman-refactoring-30-days/day15
            - /src/ironman-refactoring-30-days/day16
            - /src/ironman-refactoring-30-days/day17
            - /src/ironman-refactoring-30-days/day18
            - /src/ironman-refactoring-30-days/day19
            - /src/ironman-refactoring-30-days/day20
            - /src/ironman-refactoring-30-days/day21
            - /src/ironman-refactoring-30-days/day22
            - /src/ironman-refactoring-30-days/day23
            - /src/ironman-refactoring-30-days/day24
            - /src/ironman-refactoring-30-days/day25
            - /src/ironman-refactoring-30-days/day26
            - /src/ironman-refactoring-30-days/day27
            - /src/ironman-refactoring-30-days/day28
            - /src/ironman-refactoring-30-days/day29
            - /src/ironman-refactoring-30-days/day30
        - title: 從無到有，使用 Go 開發應用程式
          children:
            - ['/src/ironman-start-golang-30-days/', '序']
            - /src/ironman-start-golang-30-days/day01
            - /src/ironman-start-golang-30-days/day02
            - /src/ironman-start-golang-30-days/day03
            - /src/ironman-start-golang-30-days/day04
            - /src/ironman-start-golang-30-days/day05
            - /src/ironman-start-golang-30-days/day06
            - /src/ironman-start-golang-30-days/day07
            - /src/ironman-start-golang-30-days/day08
            - /src/ironman-start-golang-30-days/day09
            - /src/ironman-start-golang-30-days/day10
            - /src/ironman-start-golang-30-days/day11
            - /src/ironman-start-golang-30-days/day12
            - /src/ironman-start-golang-30-days/day13
            - /src/ironman-start-golang-30-days/day14
            - /src/ironman-start-golang-30-days/day15
            - /src/ironman-start-golang-30-days/day16
            - /src/ironman-start-golang-30-days/day17
            - /src/ironman-start-golang-30-days/day18
            - /src/ironman-start-golang-30-days/day19
            - /src/ironman-start-golang-30-days/day20
            - /src/ironman-start-golang-30-days/day21
            - /src/ironman-start-golang-30-days/day22
            - /src/ironman-start-golang-30-days/day23
            - /src/ironman-start-golang-30-days/day24
            - /src/ironman-start-golang-30-days/day25
            - /src/ironman-start-golang-30-days/day26
            - /src/ironman-start-golang-30-days/day27
            - /src/ironman-start-golang-30-days/day28
            - /src/ironman-start-golang-30-days/day29
            - /src/ironman-start-golang-30-days/day30
        - title: 輪子們，聽口令，大部分解開始！
          children:
            - ['/src/ironman-decompose-wheels/', '序']
            - /src/ironman-decompose-wheels/day01
            - /src/ironman-decompose-wheels/day02
            - /src/ironman-decompose-wheels/day03
            - /src/ironman-decompose-wheels/day04
            - /src/ironman-decompose-wheels/day05
            - /src/ironman-decompose-wheels/day06
            - /src/ironman-decompose-wheels/day07
            - /src/ironman-decompose-wheels/day08
            - /src/ironman-decompose-wheels/day09
            - /src/ironman-decompose-wheels/day10
            - /src/ironman-decompose-wheels/day11
            - /src/ironman-decompose-wheels/day12
            - /src/ironman-decompose-wheels/day13
            - /src/ironman-decompose-wheels/day14
            - /src/ironman-decompose-wheels/day15
            - /src/ironman-decompose-wheels/day16
            - /src/ironman-decompose-wheels/day17
        - title: Laravel 原始碼分析
          children:
            - ['/src/ironman-analyze-laravel/', '序']
            - /src/ironman-analyze-laravel/day01
            - /src/ironman-analyze-laravel/day02
            - /src/ironman-analyze-laravel/day03
            - /src/ironman-analyze-laravel/day04
            - /src/ironman-analyze-laravel/day05
            - /src/ironman-analyze-laravel/day06
            - /src/ironman-analyze-laravel/day07
            - /src/ironman-analyze-laravel/day08
            - /src/ironman-analyze-laravel/day09
            - /src/ironman-analyze-laravel/day10
            - /src/ironman-analyze-laravel/day11
            - /src/ironman-analyze-laravel/day12
            - /src/ironman-analyze-laravel/day13
            - /src/ironman-analyze-laravel/day14
            - /src/ironman-analyze-laravel/day15
            - /src/ironman-analyze-laravel/day16
            - /src/ironman-analyze-laravel/day17
            - /src/ironman-analyze-laravel/day18
            - /src/ironman-analyze-laravel/day19
            - /src/ironman-analyze-laravel/day20
            - /src/ironman-analyze-laravel/day21
            - /src/ironman-analyze-laravel/day22
            - /src/ironman-analyze-laravel/day23
            - /src/ironman-analyze-laravel/day24
            - /src/ironman-analyze-laravel/day25
            - /src/ironman-analyze-laravel/day26
            - /src/ironman-analyze-laravel/day27
            - /src/ironman-analyze-laravel/day28
            - /src/ironman-analyze-laravel/day29
            - /src/ironman-analyze-laravel/day30
            - /src/ironman-analyze-laravel/day30
            - /src/ironman-analyze-laravel/day31
            - /src/ironman-analyze-laravel/day32
            - /src/ironman-analyze-laravel/day33
            - /src/ironman-analyze-laravel/day34
            - /src/ironman-analyze-laravel/day35
            - /src/ironman-analyze-laravel/day36
            - /src/ironman-analyze-laravel/day37
            - /src/ironman-analyze-laravel/day38
            - /src/ironman-analyze-laravel/day39
            - /src/ironman-analyze-laravel/day40
            - /src/ironman-analyze-laravel/day41
            - /src/ironman-analyze-laravel/day42
            - /src/ironman-analyze-laravel/day43
            - /src/ironman-analyze-laravel/day44
            - /src/ironman-analyze-laravel/day45
            - /src/ironman-analyze-laravel/day46
    - title: 專題系列文章
      children:
        - /src/the-twelve-factor-app/
    - title: 筆記
      children:
        - /src/analyze-slim-framework/
        - /src/laravel-package-development-notice/
  repo: MilesChou/articles
  repoLabel: GitHub
  editLinks: true
  editLinkText: 編輯這個頁面
